language: node_js
node_js:
  - "8.11"

dist: trusty
sudo: required
addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run lint
  - ng test
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/

notifications:
  webhooks: http://192.168.32.195:4480/spec/finished
  on_success: always
