language: node_js
node_js:
  - "8.11"

dist: trusty
addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
