language: node_js
node_js:
  - "8.11"

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

before_script:
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
